[package]
name = "linbox"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["liangzhaoyuan12"]
mail = "liangzhaoyuan12@outlook.com"

[dependencies]
glib = "0.22"
gtk = { package = "gtk4", version = "0.11.4", features = ["v4_18"] }
adw = { package = "libadwaita", version = "0.9.2", features = ["gtk_v4_18", "v1_4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "2.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "sqlite"] }
rand = "0.8"